# Generated by Django 2.1.4 on 2018-12-16 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='img',
            field=models.CharField(default='i3.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 18, 45, 4, 745884)),
        ),
    ]
