# Generated by Django 2.1.3 on 2018-12-17 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181216_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacra', to='core.Sacramento'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 2, 33, 26, 21077)),
        ),
    ]
