# Generated by Django 2.1.3 on 2018-12-17 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181217_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 2, 47, 9, 348829)),
        ),
    ]
